apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started
  namespace: prd
  labels:
    app: getting-started
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getting-started
  template:
    metadata:
      labels:
        app: getting-started
    spec:
      containers:
        - name: app
                    image: getting-started:temurin
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: getting-started
  namespace: prd
spec:
  selector:
    app: getting-started
  ports:
    - name: http
      port: 8080
      targetPort: 8080
