apiVersion: v1
kind: Service
metadata:
  name: quarkus-getting-started
  namespace: prd
spec:
  type: NodePort
  selector:
    app: getting-started
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30081
