FROM eclipse-temurin:17-jre

WORKDIR /deployments

# Copia todo o fast-jar (lib/, app/, quarkus/, quarkus-run.jar)
COPY --chown=185 target/quarkus-app/ /deployments/

ENV QUARKUS_HTTP_HOST=0.0.0.0
EXPOSE 8080
ENTRYPOINT ["java","-jar","/deployments/quarkus-run.jar"]
