name: Build Quarkus (Self-Hosted)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read
  security-events: write   # necessário para enviar SARIF ao Code Scanning

jobs:
  build:
    runs-on: self-hosted   # runner Windows na sua máquina

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # ---- Build Maven (Windows) -------------------------------------------
      - name: Build com Maven (sem testes)
        shell: cmd
        run: .\mvnw.cmd -B -DskipTests package

      # ---- Docker build (Windows/cmd) --------------------------------------
      - name: Build da imagem Docker
        shell: cmd
        run: |
          set IMAGE=quarkus-service:${{ github.sha }}
          docker build -f src/main/docker/Dockerfile.jvm -t %IMAGE% .

      # ---- Instalar Trivy no Windows (curl + Expand-Archive) ---------------------
      - name: "Instalar Trivy (Windows)"
        shell: cmd
        run: |
          set TRIVY_VERSION=0.56.2
          curl -L -o trivy.zip https://github.com/aquasecurity/trivy/releases/download/v%TRIVY_VERSION%/trivy_%TRIVY_VERSION%_Windows-64bit.zip
          powershell -Command "Expand-Archive -Path trivy.zip -DestinationPath trivy -Force"
          echo %CD%\trivy>> %GITHUB_PATH%
          trivy -v

     # ---- Trivy (image) - gate temporário: CRITICAL ------------------------
      - name: "Trivy Image (gate: CRITICAL)"
        shell: cmd
        run: |
          set IMAGE=quarkus-service:${{ github.sha }}
          trivy image --scanners vuln,secret,config ^
            --severity CRITICAL ^
            --exit-code 1 ^
            --format sarif -o trivy-image.sarif %IMAGE%

# ---- Trivy (filesystem) - gate temporário: CRITICAL -------------------
      - name: "Trivy Filesystem (gate: CRITICAL)"
        shell: cmd
        run: |
          trivy fs --scanners vuln,secret,config ^
            --severity CRITICAL ^
            --exit-code 1 ^
            --format sarif -o trivy-fs.sarif .



      # ---- Upload SARIF (categorias únicas) --------------------------------
      - name: Upload SARIF (image)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif
          category: trivy-image

      - name: Upload SARIF (fs)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif
          category: trivy-fs

      # ---- Guardar relatórios como artifacts -------------------------------
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            trivy-image.sarif
            trivy-fs.sarif
